Fix/Update JCL
* Adds requires valueOf/compareTo to Enums
* Add missing IllegalAccessException/NoSuchMethodError required for
compilation of MethodHandles
* Add SuppressWarnings/Void required by execution of Javac's doclint
(javadoc)
* Added Byte/Character/Integer/Short/Long/Boolean requested to resolve varargs (eg
case of testBug84100 or testVarargs03) with Javac